// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMWAFkImgXaqTxTTXiOuAuCuUUyihsYRI',
    appId: '1:1016408346389:web:bc70c4b2ae93a645cd231c',
    messagingSenderId: '1016408346389',
    projectId: 'login-mysql-domain',
    authDomain: 'login-mysql-domain.firebaseapp.com',
    storageBucket: 'login-mysql-domain.appspot.com',
    measurementId: 'G-NVSJPDVQLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJjJNf3HHuBvE_njr6-P672ehq0oEWnRQ',
    appId: '1:1016408346389:android:ea5177b77507d38dcd231c',
    messagingSenderId: '1016408346389',
    projectId: 'login-mysql-domain',
    storageBucket: 'login-mysql-domain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4rpjaz-fxpqQSnvtjFfpEBoBuPo7Lpt0',
    appId: '1:1016408346389:ios:cc8dc69f3ff02babcd231c',
    messagingSenderId: '1016408346389',
    projectId: 'login-mysql-domain',
    storageBucket: 'login-mysql-domain.appspot.com',
    iosBundleId: 'com.example.loginMysqlDomain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4rpjaz-fxpqQSnvtjFfpEBoBuPo7Lpt0',
    appId: '1:1016408346389:ios:cc8dc69f3ff02babcd231c',
    messagingSenderId: '1016408346389',
    projectId: 'login-mysql-domain',
    storageBucket: 'login-mysql-domain.appspot.com',
    iosBundleId: 'com.example.loginMysqlDomain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMWAFkImgXaqTxTTXiOuAuCuUUyihsYRI',
    appId: '1:1016408346389:web:b4a0dd57d20ccfe1cd231c',
    messagingSenderId: '1016408346389',
    projectId: 'login-mysql-domain',
    authDomain: 'login-mysql-domain.firebaseapp.com',
    storageBucket: 'login-mysql-domain.appspot.com',
    measurementId: 'G-EBZTQLFQ6Z',
  );
}
